Greeting.create(greet: 'Hello good man.')
Greeting.create(greet: 'Good morning!')
Greeting.create(greet: 'G-Day everyone!')
Greeting.create(greet: 'Hi there!')
Greeting.create(greet: 'Good afternnon!')
